on:
  release:
    types:
      - published # We are using published instead of created because otherwise, it would never trigger if it was first created as a draft and then published.

name: Upload Android Apk to Release

jobs:
  upload-apk-to-release:
    name: Add Android Debug Apk to Release Assets
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android
    steps:
      - uses: actions/checkout@v2
      - name: Print Release Url
        run: echo "${{ github.event.release.html_url }}"
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Add google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > robot/google-services.json
          echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 --decode > robot/src/main/assets/google-services.json
      - name: Decode Release Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.keystore
      - name: Assemble Release Apk
        id: assemble_release_apk
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$PWD/release.keystore \
            -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$KEY_PASSWORD
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: Specify Release Asset Paths
        id: asset_paths
        run:  |
          echo "::set-output name=openbot_apk_path::$(pwd)/robot/build/outputs/apk/release/robot-release.apk"
          echo "::set-output name=controller_apk_path::$(pwd)/controller/build/outputs/apk/release/controller-release.apk"
      - name: Specify Release Asset Names using Tag [${{github.event.release.tag_name}}]
        id: asset_names
        run:  |
          echo "::set-output name=openbot_name::OpenBot-$(echo ${{github.event.release.tag_name}}| sed 's/[^-a-zA-Z0-9.]/_/g'| sed 's/^v//').apk"
          echo "::set-output name=controller_name::Controller-$(echo ${{github.event.release.tag_name}}| sed 's/[^-a-zA-Z0-9.]/_/g'| sed 's/^v//').apk"
      - name: Upload OpenBot Asset
        id: upload-openbot-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.asset_paths.outputs.openbot_apk_path }}
          asset_name: ${{ steps.asset_names.outputs.openbot_name }}
          asset_content_type: application/vnd.android.package-archive
      - name: Upload Controller Asset
        id: upload-controller-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.asset_paths.outputs.controller_apk_path }}
          asset_name: ${{ steps.asset_names.outputs.controller_name }}
          asset_content_type: application/vnd.android.package-archive
